Ivakin Aleksei First Step
ok-technopolis-autumn-2022/Aleksei_Ivakin pull request #1
Opened 2022-09-28 15:46 UTC by IvAlexsay

Реализована первая версия разметки

2022-09-29 06:28 UTC, fromanywhere requested changes
Что хорошо в этой итерации: Вы делали то, что в целом, и нужно было сделать (не забегали вперед)

Я оценил использование семантических тегов, но их здесь, всё же, еще пока недостаточно

2022-09-29 06:28 UTC, fromanywhere commented on index.html
> +<html lang="en" xmlns="http://www.w3.org/1999/html">
Здесь нет ошибок, но давайте удостоверимся, что тут написано именно то, что Вы хотели

1) Аудитория приложения будет англоязычной?
2) Предназначен ли документ для xml парсера?

2022-09-29 06:28 UTC, fromanywhere commented on index.html
> +    <div id="inputField">
Здесь и ниже в документе много id
Это хорошо тогда, когда в этом есть смысл (id действительно _иногда_ играет значимую роль)
Давайте подумаем над тем, чтобы сделать их меньше

Зачем? 
id предполагает, что будет единственным на странице. Это требование легко соблюдать в небольших приложениях, и сложно, если приложение разрастается. Отсюда лучше бы избегать необоснованного использования заранее

2022-09-29 06:28 UTC, fromanywhere commented on index.html
> +        <fieldset id="tasks">
Как эта структура будет выглядеть, когда в списке будет больше записей?

Как её выразить средствами html более понятно?

2022-09-29 06:28 UTC, fromanywhere commented on index.html
> +            <label for="task">HTML</label>
Какая идея лежит здесь при использовании атрибута for? (какая функциональность ожидается?)

2022-09-29 06:28 UTC, fromanywhere commented on index.html
> +        <button id="selectAllButton">
В этой части кода есть хорошие идеи и другие

Давайте обратим внимание на то, что переключатель представляет собой группу управляющих элементов. Как это отразить в коде?

2022-09-30 11:38 UTC, IvAlexsay commented on index.html
> +    <div id="inputField">
Правильно понимаю, что id используем один на страницу на основной блок, а для составных частей лучше class использовать?

2022-09-30 11:40 UTC, IvAlexsay commented on index.html
> +        <fieldset id="tasks">
Как я предполагал, fieldset подразумевает под собой группировку элементов, а у нас их будет как раз несколько одинаковых.
Или речь идёт о том, что существует более подходящий тег для списка?

2022-09-30 11:42 UTC, IvAlexsay commented on index.html
> +            <label for="task">HTML</label>
Что при нажатии checkbox текст будет перечеркнут

2022-10-10 08:48 UTC, fromanywhere requested changes

2022-10-10 08:48 UTC, fromanywhere commented on index.html
> +                    arrow
тут должен быть текст, который описывает то, что эта кнопка делает, а не то, что на ней нарисовано

2022-10-10 08:48 UTC, fromanywhere commented on index.html
> +            <div class="mainList">
список лучше делать списком (ul li)

2022-10-10 08:48 UTC, fromanywhere commented on index.html
> +                    <button class="selectAllButton" aria-label="Выбрать все задачи">
переключатели лучше сгруппировать, задать этой группе role и озаглавить её через aria-label

2022-10-12 11:35 UTC, fromanywhere requested changes

2022-10-12 11:35 UTC, fromanywhere commented on index.html
> +                        <button class="selectAllButton" aria-label="Выбрать все задачи">
Здесь договорились на радиобаттоны на лекции
+ нужно сгруппировать переключатель в один контрол, задать ему role и «заголовок» через aria-label

2022-10-12 11:35 UTC, fromanywhere commented on index.html
> +                    <p class="countInfo">3 items left <!--
А почему всё завернулось в абзац?

2022-10-12 11:35 UTC, fromanywhere commented on index.html
> +                    <input type="button" value="delete" aria-label="Удалить задачу">
лучше через title

2022-10-12 12:28 UTC, fromanywhere approved these changes

2022-10-16 16:13 UTC, merged