Ivakin Aleksei Fourth Step
ok-technopolis-autumn-2022/Aleksei_Ivakin pull request #4
Opened 2022-11-20 18:55 UTC by IvAlexsay

2022-11-20 18:55 UTC, IvAlexsay commented
Пока только начал, добавил функции добавления и удаления задачи

2022-11-21 09:27 UTC, fromanywhere requested changes
Можно сразу подумать о том, что если весь js писать в одном файле, может быть сложно. Если бить его по нескольким файлам, как организовывать их взаимодействие?

2022-11-21 09:27 UTC, fromanywhere commented on index.js
> +    label.htmlFor = task.id + 1;
дублирование убираем в переменную

2022-11-21 09:27 UTC, fromanywhere commented on index.js
> +    img.src = "http://localhost:1234/cross.b107c138.svg"
ссылка на что-то с хешированным именем — точно плохо
предлагается всё-таки делать такое стилями

2022-11-28 14:20 UTC, IvAlexsay commented
C ссылкой на изображение пока разбираюсь.
Насчет деления файлов, не понимаю как поделить, при этом использовать одни и те же переменные.

2022-11-29 12:15 UTC, fromanywhere commented
Например, можно хранить общие переменные в объекте, который экспортируется. Тогда все потребители будут иметь одну ссылку на объект

2022-12-05 08:46 UTC, fromanywhere requested changes

2022-12-05 08:46 UTC, fromanywhere commented on buttons.js
> +    todo_app_data.tasks_li.forEach(li => li.remove());
Тут нарушение S в SOLID — Single Responsibility
Если эта функция что-то показывает, она не должна в себе что-то удалять
Лучше вынести очистку в отдельную функцию

2022-12-05 08:46 UTC, fromanywhere commented on buttons.js
> +    todo_app_data.tasks_li.forEach(li => li.remove());
Ну и заодно убрать дублирование по DRY

2022-12-05 08:46 UTC, fromanywhere commented on buttons.js
> +    unactive_tasks.forEach(task => todo_app_data.tasks_li.find(li => Number(li.id) === task.id).firstChild.firstChild.click());
Вот такое блуждание по дереву очень хрупко — если изменится вложенность, всё сломается
Кроме того, лучше вызывать обработчик напрямую, чем эмулировать клик

2022-12-05 08:46 UTC, fromanywhere commented on index.js
> +todo_app_data.all_button.addEventListener('focus', showAllTasks);
А почему фокус, когда клик?

2022-12-05 08:46 UTC, fromanywhere commented on task.js
> +    if (this.newTaskText.value.length !== 0) {
trim()

2022-12-05 08:46 UTC, fromanywhere commented on task.js
> +        todo_app_data.all_button.click();
без эмуляции клика

2022-12-05 08:46 UTC, fromanywhere commented on task.js
> +    input.addEventListener('change', checkTask)
Добавлять обработчик на каждый элемент в дереве дорого. Делаем делегирование

2022-12-05 08:46 UTC, fromanywhere commented on task.js
> +    const img = document.createElement('img');
Используем css для этого

2022-12-05 08:46 UTC, fromanywhere commented on task.js
> +    button.addEventListener('click', deleteTask);
Здесь тоже делегирование, и тогда можно не отписываться на удалении

2022-12-05 08:46 UTC, fromanywhere commented on task.js
> +        id: Date.now(),
Может быть, тогда сразу один раз возвращать строку, чтобы везде внутри не приводить к Number в цикле?

2022-12-05 08:46 UTC, fromanywhere commented on index.js
> +todo_app_data.all_button = document.getElementById('sallb');
Лучше использовать для такого классы с префиксом js-

2022-12-08 17:22 UTC, fromanywhere approved these changes
Зачтено

2022-12-08 17:22 UTC, fromanywhere commented on task.js
> +    if (task_str.length !== 0) {
Здесь лучше писать if (!task_str.length) { return }. Это называется «досрочным выходом» и снижает сложность понимания кода, потому что чем больше вложенность, тем сложнее держать это в голове. На собеседованиях такое любят

2022-12-19 20:41 UTC, merged